// 《五年 · 从写代码，到让 AI 指挥 AI》
// 一份脚本，两个剪辑版本（长版 B 站 / YouTube，短版抖音 / 小红书 / 视频号），中英双语。
//
// 每个 beat 是一次整段合成（一个 ElevenLabs 请求），比逐句合成更连贯，也更像人说话。
//   shot   画面函数名；相邻同名 beat 合成一个镜头
//   act    配乐段落；音乐按段落时长作曲
//   [tag]  只发给 Eleven v4 的表演提示（笑、叹气、兴奋……），不进字幕
//   {cue}  画面对位点：这个字被念出的时刻，镜头里用 cue('名字') 取到
//   gap / pad  这一段之后的停顿；pad 是只有画面和音乐的留白
// 文字原则：只记录截至 2026 年 10 月已经发生的事；多 Agent 编排 2024 年就有，2026 年变的是执行者靠得住了。

export const BEATS = {
  long: [
    { id: 'L01', shot: 'swarm', act: 'hook', gap: 0.15,
      zh: '[curious] 你看到的每一个光点，{dots}都是一个正在写代码的 AI。而指挥它们的……{boss}也是一个 AI。',
      en: '[curious] Every one of these lights {dots}is an AI, writing code. And the thing directing them? {boss}Also an AI.' },
    { id: 'L02', shot: 'rewind', act: 'hook', gap: 0.1,
      zh: '[laughs] 好家伙。{rew}可就在五年前，这里{cursor}只有一个光标。',
      en: '[laughs] Yeah. {rew}But five years ago, there was just... {cursor}a cursor.' },
    { id: 'L03', shot: 'title', act: 'title', pad: 0.5,
      zh: '从写代码，{t2}到让 AI 指挥 AI。这五年，{t3}我们到底是怎么开发软件的？',
      en: 'From writing code, {t2}to AI directing AI. Five years. {t3}So how did we actually get here?' },

    { id: 'L04', shot: 'ide', act: 'early',
      zh: '2021 年以前，我们打开编辑器，{type}一行一行地敲。IDE 已经很聪明：{hl}高亮、{jump}跳转、{rename}一键改名；但它只能帮你操作代码，{decide}不能替你决定写什么。',
      en: 'Before 2021, you opened your editor and {type}typed it. Line by line. The IDE was smart: {hl}highlighting, {jump}go-to-definition, {rename}one-click refactors. But it could only help you handle code. {decide}It couldn\'t decide what to write.' },
    { id: 'L06', shot: 'tab', act: 'early',
      zh: '2021 年 6 月，GitHub Copilot 推出技术预览。写一行注释，{ghost}它猜下一整段；[excited] 按一下 {tab}Tab，一整个函数就出来了。',
      en: 'June 2021: GitHub Copilot\'s technical preview. Write a comment, {ghost}and it guesses the next block. [excited] Hit {tab}Tab, and there\'s your whole function.' },
    { id: 'L07', shot: 'tab', act: 'early',
      zh: '代码，第一次不用逐字敲了。可 AI 只管补全，{push}往前推，还是靠人。',
      en: 'For the first time, code didn\'t have to be typed one character at a time. But the AI only completed. {push}Moving the work forward was still on you.' },
    { id: 'L08', shot: 'diff', act: 'early',
      zh: '再后来，你直接跟 AI 编辑器说：{prompt}“把这个函数改成异步。”2024 年，Cursor 的 Composer {multi}已经能一口气改好几个文件。',
      en: 'Then you just told your AI editor: {prompt}"Make this function async." By 2024, Cursor\'s Composer {multi}could edit several files in one go.' },
    { id: 'L09', shot: 'diff', act: 'early',
      zh: '人从写代码的，变成了指挥改代码的。可你还是要坐在编辑器前，{watch}盯着每一个 Diff。',
      en: 'We went from writing code to directing code changes. But you were still sitting in the editor, {watch}watching every single diff.' },

    { id: 'L10', shot: 'agent', act: 'agent',
      zh: '[intrigued] 然后，Agent 来了。最大的不同是：{decide}它开始自己决定下一步。',
      en: '[intrigued] Then the agents arrived. The big difference? {decide}They started deciding the next step themselves.' },
    { id: 'L11', shot: 'agent', act: 'agent',
      zh: '你说：“一刷新就掉登录，修一下。”它就自己{search}搜代码、{locate}找问题、{edit}改文件、{test}跑测试；挂了？{retry}接着查。',
      en: 'You say: "Login drops when I refresh. Fix it." And it {search}searches the code, {locate}finds the issue, {edit}edits the files, {test}runs the tests. Tests fail? {retry}It keeps digging.' },
    { id: 'L12', shot: 'term', act: 'agent',
      zh: '2024 到 2025 年，{devin}Devin、{cc}Claude Code、{codex}Codex CLI 接连登场，{move}主战场从 IDE 搬进了终端。我们关心的不再是改了哪几行，而是——{done}事儿办完没有。',
      en: 'Between 2024 and 2025, {devin}Devin, {cc}Claude Code and {codex}Codex CLI arrived. {move}The action moved from the IDE to the terminal. We stopped asking which lines it changed, and started asking: {done}is it actually done?' },

    { id: 'L13', shot: 'grid', act: 'parallel',
      zh: '[playful] 嗯……既然一个 Agent 能自己把活做完，{x10}那为什么不同时开十个？',
      en: '[playful] Hmm. If one agent can work on its own... {x10}why not run ten?' },
    { id: 'L14', shot: 'grid', act: 'parallel',
      zh: '前端、后端、迁移、老 Bug，各开一个，{iso}用 Worktree 和沙箱隔开。{app}2026 年 2 月，Codex App 发布：{gui}图形界面回来了，只是屏幕上不再是代码，而是一排正在工作的 Agent。',
      en: 'Frontend, backend, a migration, an old bug: one agent each, {iso}isolated in worktrees and sandboxes. {app}In February 2026 came the Codex app: {gui}the GUI was back, but the screen wasn\'t full of code anymore. It was full of agents, working.' },

    { id: 'L15', shot: 'overload', act: 'bottleneck',
      zh: '[sighs] 可问题来了。两个 Agent 还好，{many}十几个、几十个呢？谁先做、谁依赖谁、冲突怎么合、失败要不要再试……{memory}全靠你一个人记。',
      en: '[sighs] And then the problem showed up. Two agents? Fine. {many}A dozen? A few dozen? Who goes first, who depends on whom, how to merge, whether to retry... {memory}you had to keep all of it in your head.' },
    { id: 'L16', shot: 'overload', act: 'bottleneck',
      zh: '2026 年 4 月，OpenAI 开源 Symphony 时说得很直白：{switch}拖住工程师的，是在一堆 Agent 会话之间来回切换。',
      en: 'When OpenAI open-sourced Symphony in April 2026, they said it plainly: {switch}what slowed engineers down was switching between agent sessions.' },
    { id: 'L17', shot: 'neck', act: 'bottleneck', pad: 0.9,
      zh: '[serious] AI 能同时做很多事，人却没法同时指挥那么多 AI。{neck}瓶颈……变成了人。',
      en: '[serious] AI could do a lot of work at once. We couldn\'t direct that much AI at once. {neck}The bottleneck... was us.' },

    { id: 'L18', shot: 'bloom', act: 'drop',
      zh: '[confident] 于是，我们把“组织”本身，{handoff}也交给了 Agent。你只给一个目标：{goal}“把认证系统迁到新架构，一个老用户都不能掉线。”',
      en: '[confident] So we handed the organizing itself {handoff}to an agent. You give it one goal: {goal}"Move auth to the new architecture. Don\'t log out a single user."' },
    { id: 'L19', shot: 'bloom', act: 'drop',
      zh: '协调 Agent 先{scout}派人去查。能并行的，{fan}拆开同时做；有依赖的，{chain}排队一个个来；碰上复杂的子系统，{sub}再派一个管理者去组织。',
      en: 'The coordinator {scout}sends agents to investigate first. Work that can run in parallel {fan}gets split up. Work with dependencies {chain}waits its turn. A complicated subsystem {sub}gets its own manager, who organizes the rest.' },
    { id: 'L20', shot: 'bloom', act: 'drop',
      zh: '做完的 Agent {reclaim}立刻回收，只留下结果。原以为能并行、其实有共享依赖？{reroute}那就改成串行。{count}要几个，就组织几个。',
      en: 'Finished agents {reclaim}are reclaimed. Only their results stay. Two tasks turn out to share a dependency? {reroute}Run them in sequence. {count}As many agents as the work needs, no more.' },
    { id: 'L21', shot: 'projects', act: 'drop',
      zh: '2026 年 9 月，Cursor 推出 Projects：{coord}协调 Agent 一行代码都不写，只管规划、委派、维护上下文，{back}再把结果交给你检查。',
      en: 'In September 2026, Cursor launched Projects: {coord}a coordinator agent that writes no code at all. It plans, delegates, keeps the context, {back}and hands the results back to you to check.' },

    { id: 'L22', shot: 'archive', act: 'archive',
      zh: '[serious] 但有个细节必须说清楚：{notnew}这套架构，不是 2026 年才发明的。',
      en: '[serious] But here\'s the detail that matters: {notnew}this architecture wasn\'t invented in 2026.' },
    { id: 'L23', shot: 'archive', act: 'archive',
      zh: '早在 2024 年 12 月，Anthropic 就写过 {ow}Orchestrator-Workers：一个模型动态拆任务、分给别的模型，再汇总结果。{reliable}架构早就有了；2026 年变的，是执行者终于靠得住了。',
      en: 'Back in December 2024, Anthropic described {ow}orchestrator-workers: one model breaks a task down, hands the pieces to other models, and combines the results. {reliable}The architecture was already there. What changed in 2026 is that the workers became reliable.' },
    { id: 'L24', shot: 'loop', act: 'verify',
      zh: '靠得住，靠的是验证。需求做完，从来不只是写代码：{steps}要测试、构建、部署，还要看线上跑得怎么样。{unverified}不会验证，再多 Agent 也只是更快地产出没人验过的代码。',
      en: 'Reliable means verified. Shipping a feature was never just writing code: {steps}you test it, build it, deploy it, and watch how it runs. {unverified}An agent that can\'t verify just produces unchecked code, faster.' },
    { id: 'L25', shot: 'harness', act: 'verify',
      zh: '2026 年 2 月，OpenAI 公开了一次实验：五个月，{million}约一百万行代码，{zero}没有一行是工程师手写的。{harness}他们的活，变成了给 Agent 搭环境：看得懂架构、看得见日志、跑得通测试。',
      en: 'In February 2026, OpenAI described an experiment: five months, {million}about a million lines of code, {zero}none of it written by hand. {harness}The engineers\' job became building the environment, so agents could read the architecture, see the logs, and run the tests.' },
    { id: 'L26', shot: 'harness', act: 'verify', pad: 0.3,
      zh: '执行者能自己闭环，{letgo}管理者才敢真正放手。',
      en: 'When the workers can close the loop themselves, {letgo}the manager can finally let go.' },

    { id: 'L27', shot: 'reality', act: 'reality',
      zh: '[calm] 当然，也别想得太成熟。一个小修改，一个 Agent 就够；{ten}开十个，只会更慢更贵。{pass}三个 Agent 各自测试全过，{crash}合在一起照样崩。',
      en: '[calm] Still, don\'t overestimate where we are. A small fix needs one agent. {ten}Ten would just be slower and pricier. {pass}Three agents can each pass their own tests, {crash}and the pieces can still break when they come together.' },
    { id: 'L28', shot: 'reality', act: 'reality',
      zh: '好的协调者，不是开最多的 Agent，而是知道{when}什么时候拆、{wait}什么时候等、{together}什么时候一起验证。',
      en: 'A good coordinator doesn\'t launch the most agents. It knows {when}when to split, {wait}when to wait, and {together}when everything has to be verified together.' },

    { id: 'L29', shot: 'ladder', act: 'recap',
      zh: '回头看，这五年我们一直在做同一件事：{up}把手里的活，一层层交出去。{l1}先是敲代码，{l2}再是改代码，{l3}然后是整个任务，{l4}然后是并行的组织；{l5}现在，连拆解、委派和协调，也交了出去。',
      en: 'Looking back, we\'ve been doing one thing for five years: {up}handing work up, one level at a time. {l1}First typing code. {l2}Then editing it. {l3}Then whole tasks. {l4}Then running them in parallel. {l5}And now, even breaking down, delegating and coordinating.' },
    { id: 'L30', shot: 'ladder', act: 'recap',
      zh: '旧的方式也没消失：今天依然有人手写代码，有人只按 Tab。[playful] {ask}你呢？你现在站在第几层？',
      en: 'The old ways didn\'t disappear. People still write code by hand, and plenty of us still just press Tab. [playful] {ask}So what about you? Which level are you on?' },
    { id: 'L31', shot: 'end', act: 'end',
      zh: '[thoughtful] 下一步是什么？说实话，我不知道。五年前，我们也想不到，有一天会同时指挥十几个 AI，{other}再让另一个 AI 去指挥它们。',
      en: '[thoughtful] What comes next? Honestly, I don\'t know. Five years ago, none of us pictured directing a dozen AIs at once, {other}and then handing them to another AI to direct.' },
    { id: 'L32', shot: 'end', act: 'end', pad: 0.4,
      zh: '但至少，我们看清了：{final}它是怎么一步一步，走到今天的。',
      en: 'But at least now we can see {final}how we got here, one step at a time.' },
    { id: 'END', shot: 'endcard', act: 'end', silent: true, min: 4.2 },
  ],

  short: [
    { id: 'S01', shot: 'swarm', act: 'hook', gap: 0.1,
      zh: '[curious] 你看到的每一个光点，{dots}都是一个正在写代码的 AI。而指挥它们的……{boss}也是 AI。',
      en: '[curious] Every one of these lights {dots}is an AI, writing code. And the one directing them? {boss}Also an AI.' },
    { id: 'S02', shot: 'rewind', act: 'hook', gap: 0.1,
      zh: '可就在五年前，{cursor}这里只有一个光标。',
      en: 'Five years ago, {cursor}there was just a cursor.' },
    { id: 'S03', shot: 'tab', act: 'early',
      zh: '2021 年，Copilot 来了：写句注释，{ghost}[excited] 按一下 {tab}Tab，一整个函数。',
      en: '2021: Copilot. Write a comment, {ghost}[excited] hit {tab}Tab, get a whole function.' },
    { id: 'S04', shot: 'diff', act: 'early',
      zh: '后来，我们直接说：{prompt}“把这段改成异步。”{watch}AI 动手，人盯着 Diff。',
      en: 'Then we just said: {prompt}"Make this async." {watch}AI edits, we watch the diff.' },
    { id: 'S05', shot: 'agent', act: 'agent',
      zh: '再后来，Agent {search}自己搜代码、{edit}改代码、{test}跑测试，{move}我们从 IDE 搬进了终端。',
      en: 'Then agents {search}searched the code, {edit}changed it, {test}and ran the tests. {move}We moved from the IDE to the terminal.' },
    { id: 'S06', shot: 'grid', act: 'parallel',
      zh: '[playful] 一个不够？{x10}那就同时开十个。',
      en: '[playful] One isn\'t enough? {x10}Run ten.' },
    { id: 'S07', shot: 'overload', act: 'bottleneck', pad: 0.5,
      zh: '[sighs] 然后问题来了：{many}AI 能同时做很多事，人却没法同时指挥那么多 AI。{neck}瓶颈，变成了人。',
      en: '[sighs] Then the problem: {many}AI could do a lot at once. We couldn\'t direct that much at once. {neck}The bottleneck was us.' },
    { id: 'S08', shot: 'bloom', act: 'drop',
      zh: '[confident] 于是 2026 年，{handoff}我们把组织本身也交给了 Agent：{fan}要几个，派几个；{chain}谁先谁后，它来定；{reclaim}做完就回收，只留结果。',
      en: '[confident] So in 2026, {handoff}we handed the organizing to an agent: {fan}as many workers as needed, {chain}in whatever order, {reclaim}reclaimed when done. Only the results stay.' },
    { id: 'S09', shot: 'archive', act: 'archive',
      zh: '但注意：{notnew}这套架构，2024 年就有了。{reliable}真正变的，是 Agent 终于能自己测试、自己验证。执行者靠得住，{letgo}管理者才敢放手。',
      en: 'But this architecture {notnew}existed in 2024. {reliable}What changed is that agents can now test and verify their own work. Reliable workers, {letgo}so the manager can let go.' },
    { id: 'S10', shot: 'ladder', act: 'recap',
      zh: '五年，我们一层层往上交：{l1}敲代码、{l2}改代码、{l3}整个任务，{l5}到现在，连协调本身。{ask}你现在在第几层？评论区告诉我。',
      en: 'Five years of handing work up: {l1}typing, {l2}editing, {l3}whole tasks, {l5}and now coordination itself. {ask}Which level are you on? Tell me below.' },
    { id: 'S11', shot: 'end', act: 'end', pad: 0.3,
      zh: '下一步是什么？我不知道。但至少，{final}我们看清了，是怎么走到今天的。',
      en: 'What\'s next? I don\'t know. But {final}now we can see how we got here.' },
    { id: 'SEND', shot: 'endcard', act: 'end', silent: true, min: 2.6 },
  ],
};

// 每个平台一个成片：剪辑版本 × 语言 × 画幅，外加平台专属的那一句互动语。
// fmt：h 横屏 1920×1080 · v 竖屏 1080×1920 · p 小红书 3:4 1080×1440
export const VARIANTS = {
  bilibili: { cut: 'long', lang: 'zh', fmt: 'h', name: '五年_B站',
    override: { L30: { zh: '旧的方式也没消失：今天依然有人手写代码，有人只按 Tab。[playful] {ask}你呢？你现在站在第几层？弹幕告诉我。' } } },
  youtube: { cut: 'long', lang: 'en', fmt: 'h', name: 'FiveYears_YouTube',
    override: { L30: { en: 'The old ways didn\'t disappear. People still write code by hand, and plenty of us still just press Tab. [playful] {ask}So what about you? Which level are you on? Tell me in the comments.' } } },
  douyin: { cut: 'short', lang: 'zh', fmt: 'v', name: '五年_抖音' },
  xiaohongshu: { cut: 'short', lang: 'zh', fmt: 'p', name: '五年_小红书',
    override: { S10: { zh: '五年，我们一层层往上交：{l1}敲代码、{l2}改代码、{l3}整个任务，{l5}到现在，连协调本身。{ask}你现在在第几层？评论区聊聊。' } } },
  channels: { cut: 'short', lang: 'zh', fmt: 'v', name: '五年_视频号', safe67: true,
    override: { S10: { zh: '五年，我们一层层往上交：{l1}敲代码、{l2}改代码、{l3}整个任务，{l5}到现在，连协调本身。{ask}你现在在第几层？转给身边写代码的朋友，问问他。' } } },
  shorts: { cut: 'short', lang: 'en', fmt: 'v', name: 'FiveYears_Shorts' },
};

// 画面上的文字（中 / 英）
export const TXT = {
  title1: ['从写代码，', 'FROM WRITING CODE'],
  title2: ['到让 AI 指挥 AI', 'TO AI DIRECTING AI'],
  title3: ['我们这五年，是怎么开发软件的？', 'Five years of how we build software'],
  header: ['从写代码，到让 AI 指挥 AI', 'From writing code to AI directing AI'],
  agentsLive: ['正在工作的 Agent', 'AGENTS RUNNING'],
  canDo: ['操作代码', 'HANDLE CODE'],
  cantDo: ['决定写什么', 'DECIDE WHAT TO WRITE'],
  complete: ['补全 · AI', 'COMPLETE · AI'],
  drive: ['推进 · 人', 'DRIVE · HUMAN'],
  prompt: ['把这个函数改成异步', 'Make this function async'],
  promptShort: ['把这段改成异步', 'Make this async'],
  review: ['人工审阅', 'HUMAN REVIEW'],
  task: ['修复：刷新后登录状态丢失', 'fix: login lost on refresh'],
  nextStep: ['自己决定下一步', 'IT DECIDES THE NEXT STEP'],
  delegate: ['委托任务', 'DELEGATE THE TASK'],
  done: ['事儿办完了吗？', 'IS IT DONE?'],
  front: ['前端', 'FRONTEND'], back: ['后端', 'BACKEND'], migrate: ['迁移', 'MIGRATION'], oldbug: ['老 Bug', 'OLD BUG'],
  isolate: ['WORKTREE · 容器 · 云端沙箱', 'WORKTREES · CONTAINERS · SANDBOXES'],
  needsYou: ['等你决定', 'NEEDS YOU'],
  pings: [['谁先做？', '冲突了', '测试失败', '要重试吗？', '依赖谁？', '上下文在哪？', '可以合并吗？', '下一步？'],
          ['who first?', 'conflict', 'tests failed', 'retry?', 'depends on?', 'which context?', 'merge now?', 'next step?']],
  neck: ['瓶颈', 'THE BOTTLENECK'],
  neck2: ['是人', 'IS US'],
  goal: ['迁移认证系统 · 不掉线', 'Migrate auth · zero logouts'],
  coordinator: ['协调 Agent', 'COORDINATOR'],
  manager: ['子管理者', 'SUB-MANAGER'],
  scout: ['调查', 'SCOUT'], parallel: ['并行', 'PARALLEL'], serial: ['串行', 'SEQUENTIAL'], reclaim: ['回收', 'RECLAIMED'],
  results: ['结果', 'RESULTS'],
  asNeeded: ['要几个，组织几个', 'AS MANY AS THE WORK NEEDS'],
  noCode: ['不写代码', 'WRITES NO CODE'],
  coordJobs: ['规划 · 委派 · 维护上下文', 'PLAN · DELEGATE · KEEP CONTEXT'],
  cloud: ['云端', 'CLOUD'], local: ['本地测试', 'LOCAL TEST'],
  notNew: ['不是新发明', 'NOT NEW'],
  owTitle: ['Building Effective Agents', 'Building Effective Agents'],
  owSub: ['Anthropic · 2024 年 12 月', 'Anthropic · December 2024'],
  archBox: ['架构早就有了', 'THE ARCHITECTURE EXISTED'],
  reliable: ['执行者靠得住了', 'THE WORKERS GOT RELIABLE'],
  loop: [['写代码', '测试', '构建', '部署', '观察', '修复'], ['WRITE', 'TEST', 'BUILD', 'SHIP', 'OBSERVE', 'FIX']],
  unverified: ['没人验过的代码', 'UNCHECKED CODE'],
  closed: ['闭环', 'CLOSED LOOP'],
  emptyRepo: ['空仓库', 'EMPTY REPO'],
  linesOfCode: ['行代码', 'LINES OF CODE'],
  byHand: ['行手写', 'WRITTEN BY HAND'],
  harness: [['架构约束', '需求文档', '独立实例', '日志指标', '自动测试'], ['ARCHITECTURE', 'SPECS', 'APP INSTANCES', 'LOGS & METRICS', 'TESTS']],
  letGo: ['放手', 'LET GO'],
  slower: ['更慢 · 更贵', 'SLOWER · PRICIER'],
  oneLine: ['1 行修改', '1-LINE FIX'],
  integ: ['集成失败', 'INTEGRATION FAILED'],
  db: ['数据库', 'DATABASE'], api: ['接口', 'API'], ui: ['前端', 'FRONTEND'],
  when: [['什么时候拆', '什么时候等', '什么时候一起验证'], ['WHEN TO SPLIT', 'WHEN TO WAIT', 'WHEN TO VERIFY TOGETHER']],
  levels: [['手写代码', 'Tab 补全', '对话改代码', 'Agent 完成任务', '多 Agent 并行', 'Agent 指挥 Agent'],
           ['HAND-WRITTEN', 'TAB COMPLETE', 'CHAT EDITS', 'AGENT TASKS', 'PARALLEL AGENTS', 'AGENTS DIRECT AGENTS']],
  whichLevel: ['你在第几层？', 'WHICH LEVEL ARE YOU ON?'],
  unknown: ['下一步？', 'WHAT\'S NEXT?'],
  sign: ['IDEVLAB', 'IDEVLAB'],
  endSub: ['截至 2026 年 10 月 · 已经发生的事', 'What already happened · as of October 2026'],
};

// 年代标记：每一条同时驱动顶部的年份标尺和角落的日期标签，两者永远一致。
// [beat, cue（null 为这一段开头）, 小数年份, [中文标签, English label] | null（只移动标尺）]
// 日期均已对照原始发布核实，见 CREDITS.md。
export const MARKS = [
  ['L04', null, 2020.7, null],
  ['L06', null, 2021.49, ['2021.06 · GitHub Copilot 技术预览', 'JUN 2021 · GITHUB COPILOT PREVIEW']],
  ['L08', null, 2023.22, ['2023.03 · GitHub Copilot Chat 预览', 'MAR 2023 · COPILOT CHAT PREVIEW']],
  ['L08', 'multi', 2024.53, ['2024.07 · Cursor Composer 多文件编辑', 'JUL 2024 · CURSOR COMPOSER']],
  ['L10', null, 2024.6, ['2024 · Devin、Cursor Agent', '2024 · DEVIN, CURSOR AGENT']],
  ['L12', 'cc', 2025.15, null],
  ['L12', 'codex', 2025.29, null],
  ['L13', 'x10', 2025.37, ['2025.05 · Codex 云端并行任务', 'MAY 2025 · CODEX CLOUD, PARALLEL TASKS']],
  ['L14', 'app', 2026.09, ['2026.02 · Codex App', 'FEB 2026 · CODEX APP']],
  ['L16', null, 2026.32, ['2026.04 · OpenAI Symphony', 'APR 2026 · OPENAI SYMPHONY']],
  ['L21', null, 2026.69, ['2026.09 · Cursor Projects', 'SEP 2026 · CURSOR PROJECTS']],
  ['L23', null, 2024.97, ['2024.12 · Anthropic《Building Effective Agents》', 'DEC 2024 · ANTHROPIC, BUILDING EFFECTIVE AGENTS']],
  ['L23', 'reliable', 2026.11, null],
  ['L25', null, 2026.11, ['2026.02 · OpenAI Harness Engineering', 'FEB 2026 · OPENAI HARNESS ENGINEERING']],
  ['L27', null, 2026.78, ['2026.10 · 现在', 'OCT 2026 · NOW']],
  ['S03', null, 2021.49, ['2021.06 · GitHub Copilot', 'JUN 2021 · GITHUB COPILOT']],
  ['S04', null, 2023.22, ['2023.03 · Copilot Chat', 'MAR 2023 · COPILOT CHAT']],
  ['S04', 'watch', 2024.53, ['2024.07 · Cursor Composer', 'JUL 2024 · CURSOR COMPOSER']],
  ['S05', null, 2024.6, ['2024 · Devin、Cursor Agent', '2024 · DEVIN, CURSOR AGENT']],
  ['S05', 'move', 2025.2, ['2025.02—04 · Claude Code · Codex CLI', 'FEB–APR 2025 · CLAUDE CODE · CODEX CLI']],
  ['S06', 'x10', 2025.37, ['2025.05 · Codex 云端并行', 'MAY 2025 · CODEX CLOUD, PARALLEL']],
  ['S07', null, 2026.32, ['2026.04 · OpenAI Symphony', 'APR 2026 · OPENAI SYMPHONY']],
  ['S08', null, 2026.69, ['2026.09 · Cursor Projects', 'SEP 2026 · CURSOR PROJECTS']],
  ['S09', null, 2024.97, ['2024.12 · Anthropic', 'DEC 2024 · ANTHROPIC']],
  ['S09', 'reliable', 2026.78, null],
];

// 读音：只发给合成、不改字幕的同音替换（等长逐字替换，时间戳一一对应）。
// 多音字在这些位置容易读错：行(háng)、调(tiáo)、弹(dàn)。
export const SAY = { zh: [['一行一行', '一杭一杭'], ['一行注释', '一杭注释'], ['哪几行', '哪几杭'], ['一行代码', '一杭代码'], ['万行代码', '万杭代码'], ['一行是', '一杭是'], ['协调', '协条'], ['弹幕', '蛋幕']] };
