// 《凡人 / Ordinary》的旁白、字幕与镜头表。画面、声音、配音都从这里出发。

export const LINES = {
  p1: ['很久以前，我们还不知道世界如何运转。', 'Long ago, we did not yet know how the world worked.'],
  p2: ['但我们已经开始，为自己寻找一个位置。', 'But we had already begun to look for our place in it.'],
  a1: ['天圆地方，人居其中。', 'Heaven was round, the earth was square, and we stood between them.'],
  a2: ['天、地、人，并称三才。', 'Heaven, earth, and humankind — the three powers of the world.'],
  a3: ['女娲抟土造人。', 'Nüwa shaped us from yellow clay.'],
  a4: ['神，照着自己的形象造人。', 'God made us in His own image.'],
  a5: ['每一个文明，都把人放在了世界的中心。', 'Every civilization placed us at the center of the world.'],
  b1: ['公元二世纪，托勒密把地球放在宇宙的中心。', 'In the second century, Ptolemy placed the Earth at the center of the universe.'],
  b2: ['这幅图景，延续了一千四百年。', 'That picture lasted fourteen hundred years.'],
  b3: ['一五四三年，哥白尼把中心让给了太阳。', 'In 1543, Copernicus gave the center to the Sun.'],
  b4: ['一六一〇年，伽利略看见木星的卫星。', 'In 1610, Galileo saw moons circling Jupiter.'],
  b5: ['有些天体，根本不绕着我们转。', 'Not everything in the sky turned around us.'],
  b6: ['太阳，只是银河中几千亿颗恒星之一；', 'The Sun is one of hundreds of billions of stars in our galaxy.'],
  b7: ['银河，也只是宇宙中上千亿个星系之一。', 'Our galaxy is one of hundreds of billions more.'],
  b8: ['一九九〇年，旅行者一号在六十亿公里外回望。', 'In 1990, from six billion kilometers away, Voyager 1 looked back.'],
  b9: ['地球，是一粒暗淡的蓝点。', 'The Earth was a pale blue dot.'],
  c1: ['失去了中心，我们还有出身。', 'We had lost the center. We still had our origin.'],
  c2: ['人们曾相信，万物排成一架阶梯：神、天使、人，然后是走兽、草木、石头。', 'We believed all things stood on a great ladder: God, angels, humankind — then beasts, plants, and stones.'],
  c3: ['人站在高处，离神最近。', 'We stood near the top, closest to God.'],
  c4: ['一八五九年，达尔文出版《物种起源》。', 'In 1859, Darwin published On the Origin of Species.'],
  c5: ['阶梯倒下，长成了一棵树。', 'The ladder fell, and grew into a tree.'],
  c6: ['鱼的鳍、蝙蝠的翼、鲸的鳍肢、人的手，是同一套骨骼。', "A fish's fin, a bat's wing, a whale's flipper, a human hand — the same bones, rearranged."],
  c7: ['几乎所有生命，都由细胞构成，共用同一套遗传密码。', 'Nearly all life is built of cells, and written in the same genetic code.'],
  c8: ['我们与黑猩猩的 DNA，约有百分之九十八点八相同。', "Our DNA is nearly ninety-nine percent the same as a chimpanzee's."],
  c9: ['我们不是被单独放进这个世界的。', 'We were not placed in this world apart.'],
  c10: ['我们只是生命之树上，普通的一枝。', 'We are one ordinary branch on the tree of life.'],
  d1: ['失去了位置和出身，我们退到最后一处：思想。', 'Stripped of place and origin, we retreated to our last refuge: the mind.'],
  d2: ['笛卡尔说，我思，故我在。', 'Descartes wrote: I think, therefore I am.'],
  d3: ['理性，被看作人之为人的标志。', 'Reason became the mark of being human.'],
  d4: ['后来我们看见，思想是神经元里的电与化学。', 'Then we found that thought is electricity and chemistry, moving through neurons.'],
  d5: ['然后，我们开始制造会思考的东西。', 'And then, we began to build things that think.'],
  d6: ['一九五〇年，图灵问：机器能思考吗？', 'In 1950, Turing asked: can machines think?'],
  d7: ['一九九七年，深蓝赢下了国际象棋世界冠军。', 'In 1997, Deep Blue defeated the world chess champion.'],
  d8: ['二〇一六年，AlphaGo 走出了一步人类棋手几乎不会下的棋。', 'In 2016, AlphaGo played a move that almost no human would have played.'],
  d9: ['二〇二〇年，AlphaFold 预测出蛋白质如何折叠。', 'In 2020, AlphaFold predicted how proteins fold.'],
  d10: ['如今，它们写作、作画、编程、推理——', 'Now they write, paint, code, and reason —'],
  d11: ['回答我们的问题。', 'and answer our questions.'],
  e1: ['每一次，我们以为找到了人之所以特别的最后理由；', 'Each time, we thought we had found the last reason we were special.'],
  e2: ['每一次，知识都把它还给了自然。', 'Each time, knowledge gave it back to nature.'],
  e3: ['科学所做的，也许只有一件事：', 'Perhaps science has only ever done one thing:'],
  e4: ['把人，从神坛上请下来。', 'it has brought us down from the altar.'],
  e5: ['我们不在宇宙的中心，不在造物的顶端，也不是唯一会思考的存在。', 'We are not at the center of the universe, not at the summit of creation, and not the only things that think.'],
  e6: ['我们很平凡。', 'We are ordinary.'],
};

// 屏幕上的对话
export const SCREEN = {
  q: ['我们是什么？', 'What are we?'],
  r1: ['你们问过火，问过星空，问过自己的身体。', 'You asked the fire. You asked the stars. You asked your own bodies.'],
  r2: ['现在，你们在问我。', 'Now you are asking me.'],
};

export const LABELS = {
  one: ['第一重 · 位置', 'I · PLACE'],
  two: ['第二重 · 起源', 'II · ORIGIN'],
  three: ['第三重 · 心智', 'III · MIND'],
  title: ['凡人', 'ORDINARY'],
};

// 档案图说明（纪录片式小字）
export const CAPTIONS = {
  tianyuan: ['天圆地方 · 《周髀算经》盖天说', 'Round heaven, square earth · Zhoubi Suanjing'],
  fuxi: ['伏羲女娲图 · 唐 · 新疆阿斯塔那出土', 'Fuxi and Nüwa · Tang dynasty · Astana, Xinjiang'],
  adam: ['创造亚当 · 米开朗基罗 · 约 1511', 'The Creation of Adam · Michelangelo · c. 1511'],
  nut: ['天空女神努特 · 古埃及', 'Nut, goddess of the sky · Ancient Egypt'],
  vitruvian: ['维特鲁威人 · 达·芬奇 · 约 1490', 'Vitruvian Man · Leonardo da Vinci · c. 1490'],
  ptolemy: ['托勒密体系 · 塞拉里乌斯《和谐大宇宙》· 1660', 'The Ptolemaic system · Cellarius, Harmonia Macrocosmica · 1660'],
  flammarion: ['弗拉马利翁版画 · 1888', 'The Flammarion engraving · 1888'],
  copernicus: ['哥白尼体系 · 1543', 'The Copernican system · 1543'],
  galileo: ['伽利略观测记录 · 1610', "Galileo's observations · 1610"],
  paleblue: ['暗淡蓝点 · 旅行者一号 · 1990', 'Pale Blue Dot · Voyager 1 · 1990'],
  chain: ['存在巨链 · 瓦拉德斯 · 1579', 'The Great Chain of Being · Valadés · 1579'],
  darwin: ['"I think" · 达尔文笔记 · 1837', '"I think" · Darwin\'s notebook · 1837'],
  dna: ['遗传密码 · 64 个密码子', 'The genetic code · 64 codons'],
  huxley: ['长臂猿、猩猩、黑猩猩、大猩猩、人 · 赫胥黎 · 1863', 'Gibbon, orang, chimpanzee, gorilla, man · Huxley · 1863'],
  descartes: ['松果体与灵魂 · 笛卡尔 · 1664', 'The pineal gland and the soul · Descartes · 1664'],
  cajal: ['浦肯野细胞 · 卡哈尔 · 1899', 'Purkinje cells · Ramón y Cajal · 1899'],
  turing: ['《计算机器与智能》· 图灵 · 1950', 'Computing Machinery and Intelligence · Turing · 1950'],
  chess: ['深蓝 对 卡斯帕罗夫 · 1997', 'Deep Blue vs. Kasparov · 1997'],
  go: ['AlphaGo 对 李世石 · 第二局 第 37 手 · 2016', 'AlphaGo vs. Lee Sedol · Game 2, Move 37 · 2016'],
  protein: ['AlphaFold · 2020', 'AlphaFold · 2020'],
};

// 镜头表：kind 为画面函数；lines 依次念出；lead/gap/tail 为留白（秒）；min 为最短时长；xf 为与上一镜头的叠化
export const SHOTS = [
  { kind: 'storm', lines: ['p1'], lead: 12.5, tail: 1.2, min: 18, xf: 0 },
  { kind: 'profileUp', lines: ['p2'], lead: 1.2, tail: 3.0, min: 9.5, xf: 1.4 },
  { kind: 'cave', lines: [], min: 5.5, xf: 1.6 },
  { kind: 'tianyuan', lines: ['a1', 'a2'], lead: 0.8, tail: 1.4, caption: 'tianyuan', xf: 1.4 },
  { kind: 'fuxi', lines: ['a3'], lead: 0.8, tail: 1.6, min: 6, caption: 'fuxi', xf: 1.2 },
  { kind: 'adam', lines: ['a4'], lead: 0.6, tail: 1.6, min: 6, caption: 'adam', xf: 1.2 },
  { kind: 'nut', lines: [], min: 3.6, caption: 'nut', xf: 1.0 },
  { kind: 'vitruvian', lines: ['a5'], lead: 0.4, tail: 2.0, caption: 'vitruvian', xf: 1.0 },
  { kind: 'ptolemy', lines: ['b1', 'b2'], lead: 0.6, gap: 1.0, tail: 1.2, caption: 'ptolemy', xf: 1.4 },
  { kind: 'flammarion', lines: [], min: 5.0, caption: 'flammarion', xf: 1.2 },
  { kind: 'copernicus', lines: ['b3'], lead: 0.6, tail: 3.2, min: 8, caption: 'copernicus', xf: 1.2 },
  { kind: 'galileo', lines: ['b4', 'b5'], lead: 0.5, gap: 0.6, tail: 1.0, caption: 'galileo', xf: 1.0 },
  { kind: 'zoom', lines: ['b6', 'b7'], lead: 1.4, gap: 1.6, tail: 2.6, min: 14, xf: 1.2 },
  { kind: 'paleblue', lines: ['b8', 'b9'], lead: 1.0, gap: 1.2, tail: 4.6, caption: 'paleblue', label: 'one', xf: 1.6 },
  { kind: 'chain', lines: ['c1', 'c2', 'c3'], lead: 1.0, gap: 0.7, tail: 1.0, caption: 'chain', xf: 1.6 },
  { kind: 'darwin', lines: ['c4'], lead: 0.6, tail: 1.0, min: 5.5, caption: 'darwin', xf: 1.0 },
  { kind: 'ladder', lines: ['c5'], lead: 0.8, tail: 3.6, min: 8, xf: 1.0 },
  { kind: 'limbs', lines: ['c6'], lead: 0.6, tail: 1.6, min: 9, xf: 1.2 },
  { kind: 'dna', lines: ['c7'], lead: 0.6, tail: 1.6, min: 7, caption: 'dna', xf: 1.2 },
  { kind: 'huxley', lines: ['c8'], lead: 0.8, tail: 2.0, min: 8, caption: 'huxley', xf: 1.2 },
  { kind: 'tree', lines: ['c9', 'c10'], lead: 0.8, gap: 0.8, tail: 4.6, label: 'two', xf: 1.4 },
  { kind: 'descartes', lines: ['d1', 'd2', 'd3'], lead: 1.0, gap: 0.7, tail: 1.0, caption: 'descartes', xf: 1.6 },
  { kind: 'neurons', lines: ['d4'], lead: 0.6, tail: 2.6, min: 9, caption: 'cajal', xf: 1.2 },
  { kind: 'machines', lines: ['d5'], lead: 0.3, tail: 0.8, min: 5.5, xf: 1.0 },
  { kind: 'turing', lines: ['d6'], lead: 0.4, tail: 1.6, min: 6, caption: 'turing', xf: 0.6 },
  { kind: 'chess', lines: ['d7'], lead: 0.3, tail: 1.2, min: 5.5, caption: 'chess', xf: 0.5 },
  { kind: 'go', lines: ['d8'], lead: 0.3, tail: 1.6, min: 7, caption: 'go', xf: 0.5 },
  { kind: 'protein', lines: ['d9'], lead: 0.3, tail: 1.2, min: 5.5, caption: 'protein', xf: 0.5 },
  { kind: 'streams', lines: ['d10', 'd11'], lead: 0.2, gap: 0.3, tail: 0.6, min: 6, xf: 0.4, hardOut: true },
  { kind: 'screen', lines: [], min: 19, label: 'three', xf: 0, silenceBefore: 2.6 },
  { kind: 'profiles', lines: ['e1', 'e2'], lead: 1.2, gap: 0.9, tail: 1.2, min: 10, xf: 1.6 },
  { kind: 'descend', lines: ['e3', 'e4', 'e5'], lead: 0.8, gap: 1.0, tail: 1.6, min: 16, xf: 1.6 },
  { kind: 'black', lines: ['e6'], lead: 1.4, tail: 2.4, min: 5, xf: 1.6 },
  { kind: 'title', lines: [], min: 7.5, label: 'title', xf: 0 },
  { kind: 'credits', lines: [], min: 7, xf: 1.0 },
];
